language: R
cache: packages
matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode12
r_github_packages:
  - r-lib/remotes
after_success:
  - Rscript -e 'library(covr); codecov()'
before_install:
  - sudo apt-get install libglu1-mesa-dev
after_success:
  - Rscript -e 'library(covr); codecov()'
