language: R
cache: packages
matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode12
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"]; then sudo apt-get install libglu1-mesa-dev; fi
r_github_packages:
  - r-lib/remotes
after_success:
  - Rscript -e 'library(covr); codecov()'
