language: R
cache: packages
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
    osx_image: xcode12
  - stage: prepare cache
  - script: true
  - stage: test
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
env:
  global:
    - RGL_USE_NULL=TRUE
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi
r_github_packages:
  - r-lib/remotes
after_success:
  - Rscript -e 'library(covr); codecov()'
